language: ruby
rvm:
- 2.1.3
before_install:
  - wget http://mirrors.jenkins-ci.org/war/latest/jenkins.war
  - nohup java -jar jenkins.war &
env:
  matrix:
    - JENKINS_HOST="http://0.0.0.0:8080"
  global:
    secure: IFn6ExlQO9gqoMM4OxIlx7Ylcjon3WpfjQLMkDCCXh1B0odghUEnnogKnA8vG/Aaim/krGjMfEEFRUjfYN8yLnK5Up5Nsy0tzU0t1U+Kcm4rQEPK8tnOE+qlrciaYTyZb2vyRdIz2cmFeKufC2aF8eKLg0ArlQtLm3SjBVRO2/M=
deploy:
  provider: rubygems
  gem: factor-connector-jenkins
  api_key:
    secure: mMY5ZBtkbojnbXBLCnMpvdokLoJU+RbeafrQ3CZpOGXK4+mg8hoY79kdNIYNImF4bhOh3G0Ol0ByCsBGcciX1hknWLyrv8ZNNxlhoDLgTozcTIi8Zyd1SkRD360LUxGn5cDOgX+7o226zh6p2B742dVcgIf8Y469cGxT855DpBg=
  on:
    tags: true
    all_branches: true
